services: 

  sales-db:
    image: mongo:latest
    container_name: sales-db
    restart: always
    networks:
      - sales-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
      - 28017:28017

  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    hostname: sales-rabbit
    networks:
      - sales-network
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  product-api:
    build: './product-api'
    container_name: product-api
    depends_on:
      - product-db
      - sales-rabbit
    networks:
      - sales-network
    environment:
      - PORT=3001
      - API_SECRET=5GEFEBCR6P24EF16E026D410FPKZ3S1A
      - DB_HOST=product-db
      - DB_NAME=product-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - RABBIT_MQ_HOST=sales-rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=3002
    ports:
      - 3001:3001

  sales-api:
    build: './sales-api'
    container_name: sales-api
    depends_on:
      - sales-db
      - sales-rabbit
      - product-api
    networks:
      - sales-network
    environment:
      - PORT=3002
      - SECRET = 5GEFEBCR6P24EF16E026D410FPKZ3S1A
      - DB_PORT=27017
      - DBHOST=sales-db
      - DBUSER=admin
      - DBPASS=123456
      - RABBITMQURL=amqp://guest:guest@sales-rabbit:5672/
      - PRODUCT_API_URL=http://product-api:3001/api/produtos
      - NODE_ENV=container
    ports:
      - 3002:3002

  auth-api:
    build: './auth-api'
    container_name: auth-api
    depends_on:
      - auth-db
    networks:
      - sales-network
    environment:
      - PORT=3000
      - SECRET = 5GEFEBCR6P24EF16E026D410FPKZ3S1A
      - DB_PORT=5432
      - DBHOST=auth-db
      - DBUSER=admin
      - DBPASS=123456
      - DBNAME=auth-db
    ports:
      - 3000:3000

networks:
  sales-network:
    driver: bridge